"""Add products_proof and ai_verified to seller verification

Revision ID: 390459da736a
Revises: e2e3c45f4182
Create Date: 2026-08-10 01:58:25.308269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390459da736a'
down_revision: Union[str, Sequence[str], None] = 'e2e3c45f4182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_verification_requests', sa.Column('products_proof', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('seller_verification_requests', sa.Column('ai_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_verification_requests', 'ai_verified')
    op.drop_column('seller_verification_requests', 'products_proof')
    # ### end Alembic commands ###
